### ISSUE TITLE
Set up workflows using Chart Lint and Chart Releaser

### ISSUE THREAD

**Issue by onedr0p** [petio-team/petio-charts#1]
Some examples:

#### Release:

https://github.com/k8s-at-home/charts/blob/master/.github/workflows/charts-release.yaml

#### Linting:

https://github.com/k8s-at-home/charts/blob/master/.github/workflows/charts-lint-test.yaml

@BeryJu let me know if you to tackle this or I can do it.

**Comment by BeryJu** [comment]
@onedr0p Feel free to go ahead, you have more expertise with those tools than I do

**Comment by onedr0p** [comment]
Great, I'll try to knock it out this weekend.
